### ISSUE TITLE
Support for alternatives implementations: TruffleRuby, JRuby, etc

### ISSUE THREAD

**Issue by eregon** [actions/setup-ruby#20]
There are multiple implementations of Ruby (see for example https://www.ruby-lang.org/en/about/).
Ruby library (gem) maintainers like to test against these other Ruby implementations in CI, to make sure their library works on that implementation too.

Should `actions/setup-ruby` be able to setup those Ruby implementations?
Or should it be a separate repository to setup those Ruby implementations?

I think having it in `actions/setup-ruby` would be more convenient, as one would be able to reuse the same workflow file for testing both on MRI and e.g. on JRuby and on TruffleRuby:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6.x', 'jruby-9.2.8.0', 'truffleruby-19.2' ]
    name: Ruby ${{ matrix.ruby }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ruby hello.rb
```

I think most alternative Ruby implementations provide their own binaries (while MRI does not), so the setup is usually fairly simple, and usually consists of just downloading + adding to PATH, sometimes with an extra command to run.
For instance for TruffleRuby it's just:
```bash
curl -L https://github.com/oracle/truffleruby/releases/download/vm-$VERSION/truffleruby-$VERSION-linux-amd64.tar.gz | tar xz
export PATH="$PWD/truffleruby-$VERSION-linux-amd64/bin:$PATH"
$PWD/truffleruby-$VERSION-linux-amd64/lib/truffle/post_install_hook.sh
```
