### ISSUE TITLE
Ruby 2.6.4 support

### ISSUE THREAD

**Issue by xijo** [actions/setup-ruby#24]
Essentially the same problem as #8.

Since `2.6.4` is a release for security reasons everyone should be able update ASAP, which gives the topic a certain urgency.

Has anyone found a way to install a specific ruby version manually?

Thanks in advance,
Jo

**Comment by dentarg** [comment]
> Has anyone found a way to install a specific ruby version manually?

I don't think you are allowed to, but you can use Docker. Example using the [official images](https://github.com/docker-library/ruby).

```yaml
name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
    container:
      image: ruby:2.6.2
```

**Comment by bobmaerten** [comment]
Too bad 2.6.4 is not supported (even in v1.1.0). Container specification is much longer to build (1m30 vs 30s)

**Comment by MSP-Greg** [comment]
Using rvm with ruby-head takes a bit under 60 seconds, other versions should be similar.  Example workflow in ruby/ruby.

Regardless, I would prefer that current versions be pre-installed...

**Comment by paul** [comment]
And now Ruby is up to 2.6.5, Heroku and CircleCI already have updates for it. Should we just assume this `setup-ruby` action will out-of-date, and use the docker form of workflows instead?

**Comment by ain** [comment]
`ruby:2.6.4` fetch took 42s. There's no build, it'll just fetch all layers. Quite reasonable.

**Comment by elalemanyo** [comment]
@ain I am trying to use docker to install `ruby:2.6.4`, that works great. But after I need to add `libpq-dev` to be able to use Postgres, I was doing this:
```
    - name: Install required package for Postgres
      run: |
        sudo apt-get install libpq-dev
```

But GitHub Actions is not liking it: `sudo: not found`
I am doing something wrong?

**Comment by clupprich** [comment]
@elalemanyo you don‘t need to use `sudo`, just leave it off

**Comment by elalemanyo** [comment]
@clupprich great without sudo looks to work, but now I have issues with yarn 😔
I install node like this:
```
    steps:
    - uses: actions/checkout@v1

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 8.10.x
```

So after I can install all with yarn:
```
    - name: Setup Yarn
      run: |
        yarn install
```

But I am getting this error: `yarn: not found`
