### ISSUE TITLE
Using action with Rails

### ISSUE THREAD

**Issue by AstmDesign** [actions/setup-ruby#26]
Guys, I'm trying to using actions  with rails application, actually the workflow passing well but the 
workflow console not giving me any outputs!!
you can see the attached screens, I want to know exactly what's the best practises to using actions with rails apps  

BTW I also used simple example to test the actions and found it also passed without giving me any outputs in the workflow console 

```
name: Greeting from Astm

on: [push, pull_request]

jobs:
  job1:
    name: Build rails app environment
    runs-on: ubuntu-16.04.6
    steps:
    - name: Install the OS
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
```

<img width="585" alt="Screen Shot 2019-09-12 at 2 24 19 PM" src="https://user-images.githubusercontent.com/6522659/64784136-b0712c00-d569-11e9-8968-00a7c0a105e9.png">

<img width="1238" alt="Screen Shot 2019-09-12 at 2 22 38 PM" src="https://user-images.githubusercontent.com/6522659/64784127-ab13e180-d569-11e9-91ab-b3e456a3b3cb.png">
