### ISSUE TITLE
Support .ruby-version

### ISSUE THREAD

**Issue by scottohara** [actions/setup-ruby#31]
Many ruby projects include a `.ruby-version` file in the root directory, containing the version of Ruby needed.

Tools such as `rvm`, `rbenv` and `chruby` all recognise and use this file.

This is not unlike the `.nvmrc` file often used in Node projects, and the `setup-node` action has a discussion on potentially using the contents of that file as the node version of no `with:` argument is specified. (https://github.com/actions/setup-node/issues/32)

I would suggest that `setup-ruby` might consider a similar approach, where if no explicit ruby version is given, look for a `.ruby-version` file and use the version contained within.

**Comment by tisba** [comment]
I was wondering if there is a workaround available, like

```yml
- name: Set up Ruby
  uses: actions/setup-ruby@v1
  with:
    ruby-version: "{{ cat('.ruby-version') }}"
```

However I was not able to figure out how to do that yet :(

**Comment by sobstel** [comment]
I found a workaround [in actions/setup-node repo](https://github.com/actions/setup-node/issues/32#issuecomment-525791142).

```
- name: Read .ruby-version
  run: echo "::set-output name=RUBY_VERSION::$(cat .ruby-version)"
  id: rbenv

- name: Use Node.js (.nvmrc)
  uses: actions/setup-ruby@v1
  with:
    ruby-version: "${{ steps. rbenv.outputs. RUBY_VERSION }}"
```
