### ISSUE TITLE
Ruby version ignored

### ISSUE THREAD

**Issue by fbjork** [actions/setup-ruby#32]
I have the following in my config, but the Ruby version defaults to 2.6.3
Any idea what's wrong?

```
      - name: Setup Ruby
        uses: actions/setup-ruby@v1.0.0
        with:
          ruby-version: '2.5.5'
```

This is the output:
```
Run actions/setup-ruby@v1.0.0
2
  with:
3
    ruby-version: 2.5.5
4
    version: >= 2.4
5
sudo ln -sf /opt/hostedtoolcache/Ruby/2.6.3/x64/bin/ruby /usr/bin/ruby
6
##[add-path]/opt/hostedtoolcache/Ruby/2.6.3/x64/bin
```
