### ISSUE TITLE
2.6.3 not found

### ISSUE THREAD

**Issue by philipengberg** [actions/setup-ruby#50]
Since last night, we're basically seeing [this](https://github.com/actions/runner/issues/283#issue-550349488) error output for all of our builds.

```
Run actions/setup-ruby@v1
##[error]Version 2.6.3 not found
##[error]Node run failed with exit code 1
```

**Comment by scelis** [comment]
Looks like they updated to `2.6.5`. I would recommend changing your workflow to use:

```
      - name: Select Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
```
