### ISSUE TITLE
Version 2.6.3 not found error

### ISSUE THREAD

**Issue by adbeelitamar** [actions/setup-ruby#56]
Is ruby version 2.6.3 not supported anymore by this action ? I'm specifying exact version as follows:

```
- name: Set up Ruby 2.6
  uses: actions/setup-ruby@v1
  with:
    ruby-version: 2.6.3
```
And, I'm getting the following error:
```
Run actions/setup-ruby@v1
  with:
    ruby-version: 2.6.3
##[error]Version 2.6.3 not found
##[error]Node run failed with exit code 1
```

If I do `2.6` or `2.6.x` it gets version 2.6.5. Is there any other way to force the use of the version i want?
