### ISSUE TITLE
setup-ruby fails on macos-latest

### ISSUE THREAD

**Issue by kerrmarin** [actions/setup-ruby#63]
A simple workflow like:

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Test
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.0'
```

"Succeeds" but when you look at the logs:

```
 Setup environment
1s
(node:1184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Run actions/setup-ruby@v1
(node:1184) UnhandledPromiseRejectionWarning: Error: The process 'sudo' failed with exit code 1
    at ExecState._setResult (/Users/runner/runners/2.165.2/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:547:25)
    at ExecState.CheckComplete (/Users/runner/runners/2.165.2/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:530:18)
    at ChildProcess.<anonymous> (/Users/runner/runners/2.165.2/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:430:27)
    at ChildProcess.emit (events.js:210:5)
sudo ln -sf /Users/runner/hostedtoolcache/Ruby/2.7.0/x64/bin/ruby /usr/bin/ruby
ln: /usr/bin/ruby: Operation not permitted
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:1184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
